version: '3.4'

services:
  app:
    image: webdevops/php-nginx-dev:7.4
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
    ports:
      - 10346:80
    volumes:
      - ./:/app
  mysql:
    image: mariadb:10.1.38
    environment:
      MYSQL_ROOT_PASSWORD: dbay1!
      MYSQL_USER: root
      MYSQL_PASSWORD: dbay1!
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: dbay1!
      MYSQL_USER: root
      MYSQL_PASSWORD: dbay1!
    ports:
      - 10347:80
    depends_on:
      - mysql
volumes:
  data:
